# Generated by Django 4.2.4 on 2023-08-25 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conferenceroom',
            old_name='capcity',
            new_name='capacity',
        ),
    ]
